version: 2.1

orbs:
  python: circleci/python@1.5.0
  aws-ecr: circleci/aws-ecr@8.2.1
  aws-ecs: circleci/aws-ecs@3.2.0
  node: circleci/node@5.1.0
  jira: circleci/jira@1.3.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - node/install:
          node-version: '14.18.1'
      - run: npm install -g --force @quasar/cli@1.3.2  @quasar/app@2.4.3 quasar@1.22.1  @quasar/extras@1.15.5 @quasar/quasar-app-extension-qmarkdown@1.4.4
      - run: npm update -g @quasar/cli
      - persist_to_workspace:
           root: workspace
      - run:
          name: APT update
          command: 'sudo apt update'
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Install UI
          command: echo "Installed UI!"
      - run:
          name: Build UI
          command: echo "Built UI"
      - run:
          name: Copy UI
          command: echo "Copied UI to Workspace"
      - run:
          name: Run tests
          command: echo "Ran tests!"

workflows:
  build-and-push:
    jobs:
      - build-and-test
